# If the plugin is enabled or not
# This setting will be changed from in-game using the /hibernator command
# Default: true
enabled: true

# Server TPS when in hibernation
# Setting this lower than 0.5 may crash your server!
# Default: 1
hibernation-tps: 1

# Unload chunks when hibernation starts
# Default: true
unload-chunks: true

# Delay, in seconds, between the last player disconnecting and the hibernation start
# Default: 30
player-leave-delay: 30

# Delay, in seconds, between the server start and the hibernation start
# Please note that this delay does not work when reloading the server!
# Default: 10
server-start-delay: 10

# Message displayed to a player when he wakes up the server from hibernation
player-wake-message: '<b><gradient:#7DC9EF:#506CC0>Hibernator</gradient></b>
\n\n<yellow>The server has woken up from hibernation.<yellow>
\n<green>You can rejoin now.</green>'

# Log a message when turning hibernation on and off
# Default: true
log-hibernation: true

# Log info about unloading chunks
# Default: false
log-chunk-unload: false

# Log a message when hibernation is scheduled
# Default: false
log-schedule: false